### ISSUE TITLE
Cannot access Admin page from Rhino SpecklePanel

### ISSUE THREAD

**Issue by tsvilans** [speckleworks/SpeckleRhino#225] opened 2018-12-07 17:24 UTC
Step 0: 
- [ ] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
Pressing Admin button in Account settings should take you to the admin page.

#### Actual Behaviour
`Cannot GET /admin` pops up instead. Admin should be at root ( `/` instead of `/admin`).

#### Affected Projects
Does this issue propagate to other dependencies or dependants? If so, list them here!

#### Proposed Solution (if any)
Change API call to root, not `/admin`

**Comment by didimitrie** [comment] 2019-01-12 09:52
closing as it's a dupe of #223

**Closed by didimitrie** 2019-01-12 09:52 UTC
