### ISSUE TITLE
Web socket disconnect

### ISSUE THREAD

**Issue by MrAlex8** [speckleworks/SpeckleRhino#226] opened 2018-12-12 12:28 UTC
#### Expected Behaviour
Open gh script to find speckle nodes bring my data through

#### Actual Behaviour
Open gh script to find speckle nodes are red and wont bring my data through even after a forced refresh

**Comment by didimitrie** [comment] 2018-12-12 12:36
@MrAlex8 , if i understand correctly the repoduction steps should be as follows: 
- create gh script with some senders/receivers
- save it & close it
- open it up again: receivers are in panic mode

Will look into it later on today!

**Comment by didimitrie** [comment] 2018-12-14 17:13
The way we solved this currently is to recreate the old receivers next to the old ones, and re-wire the defintion to use the newly created ones, and then delete the old ones. 

It's most probably a bug I introduced, but since it's not an issue going forward, it won't be fixed.

**Comment by didimitrie** [comment] 2019-01-18 09:51
Okay, a bit more data on reproduction: copy & pasting receivers will cause this error

**Comment by didimitrie** [comment] 2019-06-05 15:49
i think this is now closed; didn't get any other reports of it (albeit apparently on some systems, when they go to sleep, things happen). We will re-open as needed

**Closed by didimitrie** 2019-06-05 15:49 UTC
Labels: bug
